export const topics = [
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Neural Networks",
  "Computer Vision",
  "Natural Language Processing",
  "Data Science",
  "Statistics",
  "Python Programming",
  "R Programming",
  "Database Management",
  "SQL",
  "Big Data",
  "Data Warehousing",
  "Data Mining",
  "Web Development",
  "HTML",
  "CSS",
  "JavaScript",
  "ReactJS",
  "VueJS",
  "AngularJS",
  "Cybersecurity",
  "Ethical Hacking",
  "Cloud Computing",
  "AWS",
  "Azure",
  "Google Cloud",
  "Blockchain",
  "Cryptocurrency",
  "Digital Marketing",
  "Search Engine Optimization",
  "Social Media Marketing",
  "Project Management",
  "Agile Methodology",
  "Scrum",
  "Business Analytics",
  "Financial Modeling",
  "Business Intelligence",
  "Business Strategy",
  "Business Management",
  "Entrepreneurship",
  "Leadership",
  "Communication Skills",
  "Soft Skills",
  "Personal Development",
  "Career Development",
  "Chemistry",
  "Physics",
  "Biology",
  "Mathematics",
  "Algebra",
  "Geometry",
  "Hellenistic Poetry",
  "Greek Mythology",
  "Ancient Greek History",
  "Environmental Science and Climate Change",
  "The History and Impact of Social Media",
  "The Study of Human Behavior and Psychology",
  "Understanding the Global Political Landscape",
  "The Science of Nutrition and Healthy Eating",
  "The Study of Different World Religions",
  "The Art and Architecture of Ancient Civilizations",
  "The History and Evolution of Technology",
  "The Importance of Diversity and Inclusion",
  "The Study of Creative Writing and Literature",
  "The History and Impact of the Internet",
  "Artificial Intelligence and Robotics",
  "World Economics and Global Markets",
  "Music Composition and Sound Design",
  "Philosophy of Mind and Consciousness",
  "Global Health and Medicine",
  "Literary Genres and Criticism",
  "Quantum Mechanics and Relativity",
  "Brain and Cognitive Sciences",
  "Space Exploration and Astronomy",
  "Human Anatomy and Physiology",
  "Wildlife and Conservation Biology",
  "Ancient History and Archaeology",
  "Photography and Cinematography",
  "Sustainable Energy and Green Technologies",
  "Creative Coding and Interactive Design",
  "Linguistics and Language Development",
  "Cultural Studies and Diversity",
  "Performance Arts and Theater",
  "Geography and Earth Sciences",
  "Art History and Museum Studies",
  "Sports Science and Performance Training",
  "Food Science and Gastronomy",
  "Wildlife Ecology and Conservation",
  "Geology and Earth System Science",
  "Neuroscience and Neuropsychology",
  "Environmental Law and Policy",
  "Photogrammetry and Remote Sensing",
  "Public Health and Epidemiology",
  "Transportation Engineering and Planning",
  "Agricultural Science and Horticulture",
  "Marine Biology and Oceanography",
  "Building Technology and Architecture",
  "Functional Genomics and Biotechnology",
  "Public Administration and Policy Analysis",
  "Ethics and Political Philosophy",
  "Creative Writing and Poetry",
  "Sociology and Social Research",
  "Textile Design and Fashion Technology",
  "Energy Engineering and Power Systems",
  "Forensic Science and Criminal Investigation",
  "Astrophysics and Cosmology",
  "Performing Arts and Entertainment Technology",
  "Parasitology and Infectious Diseases",
  "Urban Planning and Community Development",
  "Applied Mathematics and Theoretical Physics",
  "Herpetology and Amphibian Biology",
  "Entomology and Invertebrate Zoology",
  "Human Resource Management and Organizational Behavior",
  "Aviation and Aerospace Engineering",
  "Molecular Biology and Biochemistry",
  "Landscape Architecture and Ecological Design",
  "Robotics and Mechatronics Engineering",
  "Ethnobotany and Medicinal Plants",
  "Creative and Visual Arts Therapy",
  "Financial Mathematics and Actuarial Science",
  "History of Science and Technology",
  "Ecological Economics and Environmental Policy",
  "Industrial Design and Product Development",
  "Game Design and Interactive Media",
  "Cybersecurity Risk",
  "Climate Change",
  "User Experience",
  "Global Health",
  "Quantum Computing",
  "Creative Writing",
  "Social Innovation",
  "Film Production",
  "Plant Biology",
  "Financial Markets",
  "Sustainable Agriculture",
  "Musical Performance",
  "Human Geography",
  "Speech Recognition",
  "Automotive Design",
  "Ethnic Studies",
  "International Trade",
  "Linguistics and Language",
];
