export const topics = [
    'Artificial Intelligence',
    'Machine Learning',
    'Deep Learning',
    'Neural Networks',
    'Computer Vision',
    'Natural Language Processing',
    'Data Science',
    'Statistics',
    'Python Programming',
    'R Programming',
    'Database Management',
    'SQL',
    'Big Data',
    'Data Warehousing',
    'Data Mining',
    'Web Development',
    'HTML',
    'CSS',
    'JavaScript',
    'ReactJS',
    'VueJS',
    'AngularJS',
    'Cybersecurity',
    'Ethical Hacking',
    'Cloud Computing',
    'AWS',
    'Azure',
    'Google Cloud',
    'Blockchain',
    'Cryptocurrency',
    'Digital Marketing',
    'Search Engine Optimization',
    'Social Media Marketing',
    'Project Management',
    'Agile Methodology',
    'Scrum',
    'Six Sigma',
    'Lean Management',
    'Business Analytics',
    'Financial Modeling',
]
